### ISSUE TITLE
Python3 update (and more?)

### ISSUE THREAD

**Issue by Abbotta4** [jbaiter/beetfs#2]
Hi.

I ran beetFs.py through 2to3 to update it so it would work with beets now that it uses Python3. I installed fuse-python through pip in a virtualenv and installed fuse through my package manager. I imported a test album and can get the help for the command with no problem:

```
(venv-beetfs) drew@leo% beet help mount
Usage: beet mount [options]

Options:
  -h, --help  show this help message and exit
(venv-beetfs) drew@leo% beet mount -h
Usage: beet mount [options]

Options:
  -h, --help  show this help message and exit
```

but actually mounting doesn't seem to work:

```
(venv-beetfs) drew@leo% beet mount
Traceback (most recent call last):
  File "/home/drew/venv-beetfs/bin/beet", line 8, in <module>
    sys.exit(main())
  File "/home/drew/venv-beetfs/lib/python3.8/site-packages/beets/ui/__init__.py", line 1266, in main
    _raw_main(args)
  File "/home/drew/venv-beetfs/lib/python3.8/site-packages/beets/ui/__init__.py", line 1253, in _raw_main
    subcommand.func(lib, suboptions, subargs)
TypeError: mount() missing 1 required positional argument: 'args'
(venv-beetfs) drew@leo% beet mount ./Music
Traceback (most recent call last):
  File "/home/drew/venv-beetfs/bin/beet", line 8, in <module>
    sys.exit(main())
  File "/home/drew/venv-beetfs/lib/python3.8/site-packages/beets/ui/__init__.py", line 1266, in main
    _raw_main(args)
  File "/home/drew/venv-beetfs/lib/python3.8/site-packages/beets/ui/__init__.py", line 1253, in _raw_main
    subcommand.func(lib, suboptions, subargs)
TypeError: mount() missing 1 required positional argument: 'args'
(venv-beetfs) drew@leo% 

```

Is there something I should have done differently? Is there more that needs to change to get this working again? Thank you

**Comment by seitzbg** [comment]
Indeed, can this be updated to work ?

**Comment by kopfing** [comment]
Highly interested!

**Comment by iwconfig** [comment]
> `TypeError: mount() missing 1 required positional argument: 'args'`

you probably need to remove `config` from the `mount` signature.

Here's a working version: https://github.com/iwconfig/beetfs
